### ISSUE TITLE
Problem with initializing Gem

### ISSUE THREAD

**Issue by ibariens** [Asana/ruby-asana#13]
I got the error: uninitialized constant Asana::Resources::Task::AttachmentUploading

I used the Asana gem at https://github.com/rbright/asana before, but I uninstalled this gem and double checked if the correct Asana gem is assigned in my Gemfile.lock (0.1.0) and in my bundle show. Also using irb I get the same error message when typing require 'asana'

Ruby version 2.1.4p265

**Comment by agnoster** [comment]
Hmm, according to https://rubygems.org/gems/asana 0.1.0 was never published - we just published version 0.1.1. Did you install directly from source? It's probably best to use rubygems as the source, in which case you should get 0.1.1.

(Not sure why that isn't reflected on github, looking into that now.)

**Comment by ibariens** [comment]
Thanks for looking into it agnoster!

Although I now get the right version (using rubygems or directly from github), I unfortunately still get the same error. I tried another ruby version (2.2.2) and deleting / reinstalling all my gems in rbenv, but still no success.

However I did find that when I comment out in resources/task.rb:
    #   include AttachmentUploading
    #   include EventSubscription

everything seems to work.

**Comment by agnoster** [comment]
How are you installing the gem? I assume you declare something like `gem "asana", "~> 0.1.1"` in your Gemfile and then run `bundle install` - is that correct?

**Comment by ibariens** [comment]
Indeed, `gem "asana", "~> 0.1.1"`. I also tried pulling it directly from github, but no difference there. Still the same error (I also tried it on multiple pc's.)

**Comment by agnoster** [comment]
I've tried reproducing the problem and so far been unsuccessful. Here's what I tried:

```
$ mkdir asana-gem-test
$ cd asana-gem-test/
$ rbenv version
2.2.2 (set by /Users/isaacwolkerstorfer/.rbenv/version)
$ cat > Gemfile
source "https://rubygems.org"
gem "asana", "~> 0.1.1"
$ bundle
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using multipart-post 2.0.0
Using faraday 0.9.1
Using faraday_middleware 0.9.1
Installing multi_json 1.11.1
Using faraday_middleware-multi_json 0.0.6
Using jwt 1.5.0
Using multi_xml 0.5.5
Using rack 1.6.1
Using oauth2 1.0.0
Installing asana 0.1.1
Using bundler 1.10.3
Bundle complete! 1 Gemfile dependency, 11 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ bundle exec irb
irb(main):001:0> require "asana"
=> true
```

Could you run the same commands and share the output? Maybe we'll see something in the output of bundler or... something?

**Comment by ibariens** [comment]
Strange, I tried it on a complete new VM (Ubuntu 14.04) and everything seems to work fine. Old installations both still give the same error (see below).

I got the impression that this error is out of scope of the asana gem. I will inspect my systems and compare it with the fresh VM. 

If I find something valuable for your development I will let you know. Thanks a lot for your support!


```
$ rbenv version
2.2.2 (set by /home/ibariens/.rbenv/version)
$ cat > Gemfile
source "https://rubygems.org"
gem "asana", "~> 0.1.1"
$ bundle
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using multipart-post 2.0.0
Using faraday 0.9.1
Using faraday_middleware 0.9.1
Using multi_json 1.11.1
Using faraday_middleware-multi_json 0.0.6
Using jwt 1.5.0
Using multi_xml 0.5.5
Using rack 1.6.1
Using oauth2 1.0.0
Installing asana 0.1.1
Using bundler 1.10.3
Bundle complete! 1 Gemfile dependency, 11 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ bundle exec irb
irb(main):001:0> require "asana"
NameError: uninitialized constant Asana::Resources::Task::AttachmentUploading
	from /home/ibariens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/asana-0.1.1/lib/asana/resources/task.rb:12:in `<class:Task>'
	from /home/ibariens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/asana-0.1.1/lib/asana/resources/task.rb:10:in `<module:Resources>'
	from /home/ibariens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/asana-0.1.1/lib/asana/resources/task.rb:5:in `<module:Asana>'
	from /home/ibariens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/asana-0.1.1/lib/asana/resources/task.rb:4:in `<top (required)>'
	from /home/ibariens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/asana-0.1.1/lib/asana/resources.rb:5:in `require'
	from /home/ibariens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/asana-0.1.1/lib/asana/resources.rb:5:in `block in <top (required)>'
	from /home/ibariens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/asana-0.1.1/lib/asana/resources.rb:5:in `each'
	from /home/ibariens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/asana-0.1.1/lib/asana/resources.rb:5:in `<top (required)>'
	from /home/ibariens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/asana-0.1.1/lib/asana.rb:3:in `require'
	from /home/ibariens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/asana-0.1.1/lib/asana.rb:3:in `<top (required)>'
	from (irb):1:in `require'
	from (irb):1
	from /home/ibariens/.rbenv/versions/2.2.2/bin/irb:11:in `<main>'

```

**Comment by kogre** [comment]
I have exactly the same issue. I'm on ubuntu 14.04 as well, using rvm instead of rbenv but otherwise identical output.

**Comment by kogre** [comment]
The requiring of all resources/*.rb in `/lib/asana/resources.rb` depends on the order the Dir command returns the files. According to the spec, this order is undefined.

e.g., my output for `puts Dir[File.join(File.dirname(__FILE__), 'resources', '*.rb')]` is
```
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/event_subscription.rb
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/task.rb
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/project.rb
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/team.rb
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/user.rb
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/collection.rb
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/attachment_uploading.rb
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/attachment.rb
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/story.rb
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/tag.rb
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/event.rb
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/resource.rb
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/events.rb
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/registry.rb
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/response_helper.rb
/home/koen/.rvm/gems/ruby-2.2.2/gems/asana-0.1.1/lib/asana/resources/workspace.rb
```

Meaning `task.rb` is required before `attachment_uploading.rb`, yielding the error.

If you enforce an alphabetical order, the problem is fixed.

Change
```
Dir[File.join(File.dirname(__FILE__), 'resources', '*.rb')]
```
to
```
Dir[File.join(File.dirname(__FILE__), 'resources', '*.rb')].sort
```
Alternatively, as a more robust solution, take a look at the `require_all` gem, which resolves these issues automatically.

**Comment by agnoster** [comment]
Ok, this must be something like a difference between ubuntu and Mac or something. Thanks so much for investigating and finding a solution! I will follow up on the PR #18

**Comment by agnoster** [comment]
Closed by #21, I've bumped the version to v0.1.2 which is now released!

**Comment by kogre** [comment]
Super, thank you!

**Comment by ibariens** [comment]
thanks kogre and agnoster!
